### ISSUE TITLE
Support for react-refresh v0.11.0?

### ISSUE THREAD

**Issue by AviVahl** [Jack-Works/react-refresh-transformer#13]
Heya @Jack-Works, I've noticed react-refresh@0.11.0 has been released, but react-refresh-typescript currently specifies: `"react-refresh": "0.10.x"`

Any chance for a release ensuring compatibility?

**Comment by Jack-Works** [comment]
Hi as you wished, 2.0.3 has been published.

**Comment by AviVahl** [comment]
Super quick heh. Thank you!
