### ISSUE TITLE
support react-refresh@0.13.x

### ISSUE THREAD

**Issue by Bessonov** [Jack-Works/react-refresh-transformer#15]
pnpm@7 has activated more strict checking of peer dependencies by default and fails now with:

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ react-refresh-typescript
  └── ✕ unmet peer react-refresh@"0.10.x || 0.11.x || 0.12.x": found 0.13.0
```

Not sure that changing [this line](https://github.com/Jack-Works/react-refresh-transformer/blob/main/typescript/package.json#L31) is enough. But I didn't found any problems with my [monorepo-starter](https://github.com/Bessonov/monorepo-starter).

**Comment by Jack-Works** [comment]
Thanks for your report! 2.0.5 has been released to match 0.13.0
