### ISSUE TITLE
Generated variables for react-refresh has conflicts when React hooks are used within render props

### ISSUE THREAD

**Issue by karyiteh** [Jack-Works/react-refresh-transformer#19]
Hi, I'm running into this issue: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/744

Upon further inspection on how the plugin works, it seems that it could be this transformer that is generating the variable names that has a conflict, just wondering if there are any pointers regarding where that is done, or how I should proceed?

**Comment by Jack-Works** [comment]
the temp variable is generated by TypeScript.

https://github.com/Jack-Works/react-refresh-transformer/blob/724c8a6a2c665038482fe0c81dcaf42775850ca0/typescript/src/core.ts#L232

**Comment by karyiteh** [comment]
Ah I see, I wonder if there is a way where we can use `createTempVariable()` to generate temp variables that are unique at the file scope? That way, there won't be shadowing of the temp variables that will be causing this issue.
