### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by justin-cotarla** [Jack-Works/react-refresh-transformer#7]
When using this plugin with Webpack's devserver, I cannot manage to get typescript sourcemaps to work.

Sourcemaps from `bundle.js` that Webpack generates work fine, however the typescript sourcemaps do not work at all. The sourcemaps map to transpiled js code, not ts. I've set `sourceMap` to true in `tsconfig.json`, and I've also tried setting it to inline sourcemaps to no avail.

The example in this repo does not enable sourcemaps. Is this a bug?

**Comment by Jack-Works** [comment]
Sourcemap support for typescript transformers is available out-of-box (typescript compiler will handle it). If you find the source-map is not working, it has to be something misconfigured in your project.

**Comment by Jack-Works** [comment]
I have enabled sourcemaps in the example folder in 457adcec78b984a658a88eed5a525d9b069787f6.
