### ISSUE TITLE
Problem with arrow functions and hooks

### ISSUE THREAD

**Issue by dimitriirybakovparsable** [Jack-Works/react-refresh-transformer#8]
Initially problem was described [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/365#issuecomment-845850819)

If I change example code like this
```
import { useState } from 'react'

export const Component = () => {
    const [state, setState] = useState(0)
    console.log('source map test')
    return (
        <>
            Current foobar {state}
            <button onClick={() => setState((x) => x + 1)}>Add</button>
        </>
    )
}
```

```
import { useEffect } from 'react'
import { Component } from './Component'

export const App = () => {
    useEffect(() => {
        console.log('render');
    }, []);

    return (
        <div>
            <Component />
        </div>
    )
}
```

then every change in Component will result full page reload
![image](https://user-images.githubusercontent.com/82868328/125270034-f5a34800-e311-11eb-8259-a1e3fb1af812.png)

If I will remove hooks or change declaration back to functions - everything fixes itself.
It may be connected to component losing displayName as it was described in initial comment

**Comment by Jack-Works** [comment]
I can reproduce this. Let me figure out why.

**Comment by Jack-Works** [comment]
Got the reason. Arrow function missing its name after the transform thus `isLikelyComponentType` doesn't treat it as a Component anymore.

**Comment by Jack-Works** [comment]
Please try 2.0.2

**Comment by dimitriirybakovparsable** [comment]
Yes, 2.0.2 works for me, thank you!
